### ISSUE TITLE
Cannot decode image data

### ISSUE THREAD

**Issue by FaFre** [ibrierley/flutter_map_vector_tiles#24]
I tried to get the example code running.

The image decoding is failing for the fetched files: https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/17/65466/43975.mvt?access_token=...

`"Error: ImageCodecException: Failed to decode image data.
Image source: encoded image bytes
    at Object.throw_ [as throw] (http://localhost:39407/dart_sdk.js:5041:11)
    at _engine.CkAnimatedImage.decodeFromBytes.createDefault (http://localhost:39407/dart_sdk.js:133885:19)
    at _engine.CkAnimatedImage.decodeFromBytes.ManagedSkiaObject.new (http://localhost:39407/dart_sdk.js:132149:65)
    at new _engine.CkAnimatedImage.decodeFromBytes (http://localhost:39407/dart_sdk.js:133932:43)
    at Object.skiaInstantiateImageCodec (http://localhost:39407/dart_sdk.js:173809:12)
    at instantiateImageCodec (http://localhost:39407/dart_sdk.js:128334:24)
    at instantiateImageCodec.next (<anonymous>)
    at runBody (http://localhost:39407/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:39407/dart_sdk.js:37453:7)
    at Object.instantiateImageCodec (http://localhost:39407/dart_sdk.js:128332:18)
    at binding$5.WidgetsFlutterBinding.new.instantiateImageCodec (http://localhost:39407/packages/flutter/src/painting/binding.dart.lib.js:81:17)
    at decodeImageFromList (http://localhost:39407/packages/flutter/src/painting/image_decoder.dart.lib.js:16:75)
    at decodeImageFromList.next (<anonymous>)
    at runBody (http://localhost:39407/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:39407/dart_sdk.js:37453:7)
    at Object.decodeImageFromList (http://localhost:39407/packages/flutter/src/painting/image_decoder.dart.lib.js:15:18)
    at VectorTileWidget._VectorTileLayerState.new.<anonymous> (http://localhost:39407/packages/flutter_map_vector_tile/vector_tile_plugin.dart.lib.js:2244:39)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:39407/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:39407/dart_sdk.js:37453:7)
    at http://localhost:39407/packages/flutter_map_vector_tile/vector_tile_plugin.dart.lib.js:2233:119
    at _RootZone.runUnary (http://localhost:39407/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:39407/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:39407/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:39407/dart_sdk.js:33095:17)
    at _Future.new.[_complete] (http://localhost:39407/dart_sdk.js:32935:25)
    at Object._cancelAndValue (http://localhost:39407/dart_sdk.js:37653:24)
    at http://localhost:39407/dart_sdk.js:19279:21
    at Object._runUserCode (http://localhost:39407/dart_sdk.js:37610:7)
    at http://localhost:39407/dart_sdk.js:19277:17
    at _RootZone.runUnaryGuarded (http://localhost:39407/dart_sdk.js:37211:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:39407/dart_sdk.js:31145:22)
    at _DelayedData.new.perform (http://localhost:39407/dart_sdk.js:34417:28)
    at _StreamImplEvents.new.handleNext (http://localhost:39407/dart_sdk.js:34521:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:39407/dart_sdk.js:34282:16)
    at Object._microtaskLoop (http://localhost:39407/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:39407/dart_sdk.js:37532:13)
    at http://localhost:39407/dart_sdk.js:33303:9"`

Did the format change?

**Comment by ibrierley** [comment]
Couple of questions, have you updated recently, and this is on the Master branch ?

Also is this trying to get it working in a browser ? As I can see a lot of js there..

**Comment by FaFre** [comment]
I checked out the filter branch, there it's working on my Android device.

For Web however, the spawning of isolates is not possible due to Framework limitations. I'll do some research if there's a workaround for that.

**Comment by ibrierley** [comment]
Yes, I haven't got as far as looking at the web side as yet. My understanding was there may be something possible with web workers, but I didn't want to go down that route until I was happy with how the other stuff worked. There's a lot involved with getting vector tiles working so it's hard to tell if it would ever be "stable" :D.

**Comment by FaFre** [comment]
Yeah, I came here through the big flutter_map issue, which is going on already since a couple of years :D Complicated stuff, those vector tiles. However, I'll keep an eye on this project here, and wish you good luck continuing!

**Comment by ibrierley** [comment]
Out of interest, how did the filter branch perform on your device ? Looking for a bit of general feedback on other devices to mine.

**Comment by FaFre** [comment]
At first I thought something is wrong, now I wanted to make a screenshot for you and realized it just takes ages on my old 2013 android test device it takes about 15sec to render the initial tiles after App start. When I pan around to new areas it gets slower and slower... I also built the example in release-mode but it doesn't seem to make a difference.

**Comment by ibrierley** [comment]
Thanks for the feedback. I thought it may suffer with old devices.

Out of interest, I think its probably the main.dart in the lib folder, rather than the examples folder which is the latest to test with (or try both). Also it may be worth swapping useCanvas=true and useImages=true around. useImages tries to draw to an image and then is faster after loaded, but useCanvas has some line thinning optimisations (only have one of them set to true, the other false) and doesn't use images (maybe preferable if it's not a powerful device with many cores/ram).

I'm still undecided which is preferable (and may depend on devices), so as mentioned it's all still very experimental.

Thanks again.

**Comment by FaFre** [comment]
So far I only tested with the new main.dart (not the one from examples/).

Swapping `useImages` with `useCanvas` results in only half rendered screen on my device. Some tiles just never get rendered, doesn't matter how long I wait.

But it might not be the rendering itself which causes the problems, I noticed this in my debug log while running the app in profile mode:

`2
I/flutter (11172): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/chatty  (11172): uid=10142(com.example.example) 1.ui identical 11 lines
2
I/flutter (11172): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/chatty  (11172): uid=10142(com.example.example) 1.ui identical 2 lines
2
I/flutter (11172): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/chatty  (11172): uid=10142(com.example.example) 1.ui identical 13 lines
2
I/flutter (11172): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
I/chatty  (11172): uid=10142(com.example.example) 1.ui identical 1 line
I/flutter (11172): Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction`

I guess this code is running inside the isolate, so it's not visible to the dart profiler.
The rendering might be not the problem itself, and the bottleneck is possibly somewhere else (I haven't really looked in your code).

Besides that, maybe you want to reconsider using `flutter_isolate` for your package, since it's only working on iOS and Android. I did some research and found this: https://github.com/deakjahn/flutter_isolate_web it seems to be a cross-platform solution for that. There isn't much out there when it comes to cross platforming with isolates. It seems like that could be a solution. However, I failed to implement that code in a short time to give it a shot, since I never worked with isolates before and don't want to spend much time on that...
But maybe I can contribute a decent example application, so people who stumble upon this project can give it a shot and might get interested, or contribute some test results.

**Comment by FaFre** [comment]
Mhm letting the app open for a couple of minutes and staring to pan around on zoom levels > ~15 will actually render much faster ~1-2 sec after panning to a new location. But it sometimes to "forget" to render some tiles and leaves them at a lower zoomlevel or leaves them blank.

**Comment by ibrierley** [comment]
Heya, thanks again. Out of interest, what's the device you are testing on ? I may try and see if I can borrow something similar, as it's often easier for testing then.

I haven't looked into the forgetting a tile yet, not sure if that's one that never got downloaded, or just doesn't display for some reason. I'm using my own tile layer to try and improve performance.

I'm not sold on using isolates at all, and that's why I haven't merged any of that into master. The last month or so have just been experiments with filters, styles and isolates and seeing how performant I can get them. Isolates maybe just suck up extra resources and don't achieve as much as I'd hoped...but I suspect I'll end up leaving them in there as a toggle (maybe using something like the isolate_web thing), maybe default off.

The biggest problem typically is drawing thick lines is super slow in canvas (issue with skia), which locks up the UI. So I've been trying to come at various angles, eg draw hairline strokes when moving, or at low zoom levels, and having a limited enforced style set. In some ways that original version was more slick than my recent style/filter/isolates work. So something for me to ponder. 

I think I'll probably try and pull it together bit so everything is an option and then it's a bit easier to experiment.

Thanks again

**Comment by FaFre** [comment]
Maybe you can also simulate it with an emulator and bad specs. It's an Galaxy Note 3, not the worst device from that time at all.

I was just contributing to a project couple of minutes ago, that used isolates for GeoJson decoding. In my test it even ran faster without isolates, just single threaded. Multi-threading in Dart doesn't seem to be as effective in most cases as in other well known languages what I've seen so far - but it's always also a question of the implementation and use case of course. 

For your project I think it would make sense to also offer single threaded processing. In that way you could also make use of the dart profiler, which is pretty neat finding performance issues (it doesn't seem to work with isolates from what I've tried). 

You did already a great process with it! Congratulations for that :)

**Comment by ibrierley** [comment]
Thanks for the thoughts, I think I've already done an option for not using isolates on a different branch I've just updated unimaginatively called "options" :D, where you can set useIsolates: false in the Optimisations in main.dart (not in examples). It's very much in debugging stage still, but should work similar to the other branch apart from a few tweaks like that. I'm away for a week shortly though, so won't get much change to tidy it up. You can also switch between using Images or Canvas.

I've resurrected an old tablet to test on. The problem with the emulators is simulating pinchzoom which is where for me typically the problems lie, and why I've tried isolates. If you don't use something, the ui gets blocked, but each "solution" causes another issue :D. Isolates do seem to just add another resource that's used though, it helps prevent blocking, but then it's using more resources in another way.

I'm almost wondering whether to ditch all the complexity though, as it's currently all a bit messy, go back to pure vectors (rather than options like vector to image), enforce simple fast styles.
